trigger:
- main

pool:
  name: Default 
  #vmImage: ubuntu-latest

# Building Stages
stages:
- stage: BuildApp
  displayName: Build Apps
  jobs:
  - job: BuildFrontEndApp
    displayName: Build Frontend App
    steps:
    - script: echo building frontend app
      displayName: build frontend app
    - script: echo running unit tests for frontend app
      displayName: unit test frontend

  