trigger:
- main

pool: 
  vmImage: ubuntu-latest

stages:
- stage: BuildApp
  displayName: Build Apps
  
  jobs:
  - job: BuildFrontEndApp
    displayName: Build Frontend App
    
    steps:
    - script: echo building frontend app
      displayName: build frontend app
    
    - script: each running unit tests for frontend app
      displayName: unit test frontend